### ISSUE TITLE
Alternative syntax à la IPython

### ISSUE THREAD

**Issue by Jiehong** [erszcz/docsh#1]
Hello,

Would it be possible to have an alternative syntax by using "?"?

Here are what the examples you gave would look like:

```` erlang
> recon?.
(…)
>  recon:get_state/1?.
(…)
> recon:get_state/2?.
````

**Comment by erszcz** [comment]
I'm thinking of [a more convenient syntax, one which would allow to rely on Erlang shell `<tab>`-autocompletion as much as possible](https://github.com/erszcz/docsh/blob/shell-extensions/notes.md#user_default-extensions), but not as succinct as what you propose:

```erlang
> h(lists).
> h(fun lists:keyfind/3).
> h(lists, keyfind, 3).
```

Specifically, if module `lists` is already loaded, just typing `h(fun li<tab>:keyf<tab>).` should save a couple of keystrokes (where `<tab>` means you press the TAB key to invoke autocompletion). There's some work in progress on that, but it's not finished and described in the README yet.

Unfortunately, the Erlang lexer and parser constrain the syntax we can use - that's why the proposition with `recon?.` won't work.

**Comment by Jiehong** [comment]
autocompletion would be convenient, indeed. Thanks for the quick answer!

**Comment by erszcz** [comment]
@Jiehong, for quite some time now it's possible to do `h(fun some_module:some_function/3)` and the shell will autocomplete module and function names. Check it out, it works really well!
